.TH "ILBMPP" "1" "January 2012" "ilbmpp 0.1" "Command Reference"
.SH "NAME"
ilbmpp \- Displays a textual representation of an IFF/ILBM file on the standard output
.SH "SYNOPSIS"
\fBiffpp\fR [\fIoptions\fR] [\fIfile.ILBM\fR]
.SH "DESCRIPTION"
.PP
The command \fBilbmpp\fR displays a textual representation of a given IFF file
containing ILBM form chunks, which can be used for manual inspection. If no IFF
file is specified, it reads an IFF file from the standard input.
.SH "OPTIONS"
\fB\-c\fR, \fB\-\-disable\-check\fR
.RS 4
Do not check the IFF file for validity
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Shows the usage of this command to the user
.RE
.PP
.SH "AUTHOR"
.PP
\fBSander van der Burg\fR
.br
.RS 4
Author
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2012 Sander van der Burg
.br
