#define ILBM_NUM_OF_FORM_TYPES 3

{ILBM_ID_ACBM, ILBM_NUM_OF_EXTENSION_CHUNKS, ilbmFormExtension},
{ILBM_ID_ILBM, ILBM_NUM_OF_EXTENSION_CHUNKS, ilbmFormExtension},
{ILBM_ID_PBM, ILBM_NUM_OF_EXTENSION_CHUNKS, ilbmFormExtension}
