#define ILBM_NUM_OF_FORM_TYPES 3

{"ACBM", ILBM_NUM_OF_EXTENSION_CHUNKS, ilbmFormExtension},
{"ILBM", ILBM_NUM_OF_EXTENSION_CHUNKS, ilbmFormExtension},
{"PBM ", ILBM_NUM_OF_EXTENSION_CHUNKS, ilbmFormExtension}
